---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Prune=true  # Allow deletion
    argocd.argoproj.io/sync-options: Replace=true  # Force replace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # ✅ Changed from gp2
  resources:
    requests:
      storage: 2Gi
